server:
  port: 8888
  servlet:
    context-path: /stalk
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/speak?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
  thymeleaf:
    mode: LEGACYHTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    cache: false
    servlet:
      content-type: text/html
